Edit Feature
NickPriv/FryRankFrontend pull request #104
Opened 2024-12-11 05:02 UTC by Justdoit2

Feature Flag Included:
Part 1: add edit tag for user's account login only
Part 2: display modal with design of previous create review form
Part 3: inject profiled score ranking, review text, etc into modal's review Form

2024-12-18 06:00 UTC, NickPriv commented on src/components/EditReview/EditReviewModal.jsx
> +                    <Button color="primary" onClick={toggle}>
Will be `save` instead of `toggle`

2024-12-18 06:00 UTC, NickPriv commented on src/components/EditReview/EditReviewModal.jsx
> +                    <h3>{restaurant.displayName.text}</h3>
This is probably where the existing review form gets imported

2025-01-16 01:18 UTC, Justdoit2 commented on .env.sample
> +REACT_APP_FEATURE_EDIT="true"
yea
 we can remove now. it was for temporary testing purposes

2025-01-16 07:29 UTC, NickPriv commented on src/components/EditReview/EditReviewModal.jsx
> +            onRefresh();
![Screenshot 2025-01-15 232525](https://github.com/user-attachments/assets/bef7fdc9-873f-4a85-a102-a128c02372d5)

I'm getting this error "onRefresh is not a function" after I click "Save edit" in the modal. Any idea why that might be? Did you not get that when you were testing?

2025-02-04 07:31 UTC, NickPriv commented
Everything looks good feature-wise! However, the author name for a review is not showing up; it looks like a regression from Daniel's change, can you take a look at why that is?

2025-02-04 07:34 UTC, NickPriv requested changes

2025-02-04 07:34 UTC, NickPriv commented on .env.sample
> -REACT_APP_GOOGLE_AUTH_KEY= "<KEY>"
Nit: this file change isn't needed in the commit

2025-02-04 07:34 UTC, NickPriv commented on src/components/Common/ReviewCard/index.jsx
> -                              {review.userMetadata ? review.userMetadata.username : (review.authorId ? review.authorId : review.accountId)}
this part should be retained so it gets the user metadata

2025-02-04 07:34 UTC, NickPriv commented on src/components/Common/ReviewCard/index.jsx
> +                                {review.authorId ? review.authorId : review.accountId}
this is the older version which doesn't use the user metadata; should update to have the user metadata

2025-02-04 07:34 UTC, NickPriv commented on src/constants.js
> -
nit: unnecessary file change, can remove

2025-02-04 23:50 UTC, Justdoit2 commented on src/constants.js
> -
added back default spacing

2025-02-04 23:57 UTC, Justdoit2 commented on src/components/Common/ReviewCard/index.jsx
> -                              {review.userMetadata ? review.userMetadata.username : (review.authorId ? review.authorId : review.accountId)}
fixed

2025-02-05 05:48 UTC, NickPriv requested changes

2025-02-05 05:48 UTC, NickPriv commented on src/components/Common/ReviewCard/index.jsx
> +                        {isReviewAuthor && ( <FaEdit style={{ fontSize: '24px', position: 'absolute', top: '19px', right: '15px', cursor: 'pointer' }} onClick={save} /> )}
Just a callout that using the fixed values means we should be verifying on Beta stage that the sizing works on mobile

2025-02-05 05:48 UTC, NickPriv commented on src/components/EditReview/EditReviewModal.jsx
> +        },200)
Is this necessary? We can probably use the successful create review action from the reducer to update the state. And with a failed create review action, then we could display an error. This is better than an arbitrary timeout value which could be insufficient if the user has a slow network connection

2025-02-05 05:48 UTC, NickPriv commented on src/components/EditReview/EditReviewModal.jsx
> +                        <FormGroup>
This form group is identical to this one: https://github.com/NickPriv/FryRankFrontend/blob/master/src/components/CreateReview/ReviewForm/index.jsx#L43

I suggest making it a new common component and importing it in both places

2025-02-05 05:48 UTC, NickPriv commented on src/components/EditReview/EditReviewModal.jsx
> +        },200)
Reference for the reducer actions: https://github.com/NickPriv/FryRankFrontend/blob/master/src/redux/reducers/reviews/index.js#L148

2025-02-06 03:58 UTC, oxyflush commented on .env.sample
> +
Why did this get removed from env sample?

2025-02-06 04:02 UTC, oxyflush commented on src/components/Critic/index.jsx
> +            setTimeout(async ()=> {
Referencing https://github.com/NickPriv/FryRankFrontend/pull/104/files#r1942276456 here as well due to timeout usage.

2025-02-06 08:56 UTC, Justdoit2 commented on .env.sample
> +
oohps mega brain fart

2025-02-11 07:57 UTC, Justdoit2 commented on src/components/Common/ReviewCard/index.jsx
> +                        {isReviewAuthor && ( <FaEdit style={{ fontSize: '24px', position: 'absolute', top: '19px', right: '15px', cursor: 'pointer' }} onClick={save} /> )}
as discuss yolo going straight to our fryrank beta stage

2025-02-11 08:05 UTC, NickPriv requested changes

2025-02-11 08:05 UTC, NickPriv commented on .env.sample
> +
Looks like it still needs to be added back

2025-02-11 08:05 UTC, NickPriv commented on src/components/EditReview/EditReviewModal.jsx
> +                        <FormGroup>
This part is still pending

2025-02-18 08:22 UTC, NickPriv approved these changes
LGTM!! Not only does it work but it's a good user experience as well 🔥

2025-02-19 04:02 UTC, merged