Nav Bar Changes
NickPriv/FryRankFrontend pull request #97
Opened 2024-11-05 06:24 UTC by Justdoit2

-Make header adjustable
-Integrate with other changes
-Add current links

2024-11-05 07:31 UTC, Justdoit2 commented
![Screen Shot 2024-11-04 at 11 23 05 PM](https://github.com/user-attachments/assets/9c334b98-3b1f-4b32-b140-2a8c1e198c0f)

2024-11-06 04:46 UTC, NickPriv requested changes

2024-11-06 04:46 UTC, NickPriv commented on src/components/Common/GoogleLogin/index.jsx
> +                    <p className="inline text-white">!</p>
any reason for changing the color?

2024-11-06 04:46 UTC, NickPriv commented on src/components/Common/Header/index.jsx
> +                            <NavLink href='/restaurants'>
Use `Link` from `react-router-dom` so that it doesn't reload the page while going to the other route.

2024-11-06 04:46 UTC, NickPriv commented on src/components/Common/Header/style.module.css
> +    color: #000;
Can just put "black"

2024-11-06 04:46 UTC, NickPriv commented on src/components/Common/Header/style.module.css
> +
Nit: Extra spacing

2024-11-06 04:46 UTC, NickPriv commented on src/components/Common/Header/style.module.css
> +    padding-right: 1rem;
Based on the mockup, looks like it needs padding on the left side as well to separate it from the navbar dropdown

2024-11-06 04:46 UTC, NickPriv commented on src/components/RecentReviews/index.jsx
> +};
Let's not commit this file until we're going to put something here

2024-11-12 04:38 UTC, Justdoit2 commented on src/components/Common/GoogleLogin/index.jsx
> +                    <p className="inline text-white">!</p>
daniel later

2024-11-12 06:20 UTC, NickPriv requested changes

2024-11-12 06:20 UTC, NickPriv commented on src/components/Common/GoogleLogin/index.jsx
> +                    <p className="inline text-white">!</p>
I think we mentioned removing the white text, could we do that?

2024-11-12 06:32 UTC, Justdoit2 commented on src/components/Common/GoogleLogin/index.jsx
> +                    <p className="inline text-white">!</p>
removed from daniel's pr

2024-11-12 23:53 UTC, merged