Almaniu/recent reviews
NickPriv/FryRankFrontend pull request #99
Opened 2024-11-26 04:44 UTC by Justdoit2

Get Recent Reviews and see restaurant address in React

2024-11-30 11:12 UTC, NickPriv requested changes

2024-11-30 11:12 UTC, NickPriv commented on src/components/RecentReviews/proxy.js
> +    const response = await fetch(`http://localhost:8080/api/reviews/top?count=${count}`);
This has to connect to the live backend service, not necessarily a local port. Import the constant `BACKEND_SERVICE_PATH` from [here](https://github.com/NickPriv/FryRankFrontend/blob/master/src/constants.js#L11)

2024-11-30 11:12 UTC, NickPriv commented on src/components/RecentReviews/proxy.js
> +export const fetchTopReviews = async (count = 5) => {
Move this `proxy.js` file to `src/containers/RecentReviews/index.js` to follow the existing package structure

2024-11-30 11:12 UTC, NickPriv commented on src/components/RecentReviews/index.jsx
> +        return <p>Sorry, no reviews published yet.</p>;
Because there have already been reviews published on Prod, having no reviews loaded would indicate an error in the application. It would be better to display an [ErrorBanner](https://github.com/NickPriv/FryRankFrontend/blob/master/src/components/Common/ErrorBanner/index.jsx) communicating that there was an error loading reviews.

2024-12-05 05:19 UTC, NickPriv requested changes

2024-12-05 05:19 UTC, NickPriv commented on src/components/RecentReviews/index.jsx
> +        return <p><ErrorBanner error={error} /></p>;
Why put the fry spinner and error banner inside a p tag?

2024-12-05 05:19 UTC, NickPriv commented on src/containers/RecentReviews/index.js
> +const GOOGLE_API_PATH = "https://places.googleapis.com/v1/";
Why declare this locally? Should be able to use a common constant that is also used by the saga

2024-12-05 05:19 UTC, NickPriv commented on src/containers/RecentReviews/index.js
> +const HEADER_FIELD_MASK = 'X-Goog-FieldMask';
This can also be shared with the saga file

2024-12-05 05:19 UTC, NickPriv commented on src/containers/RecentReviews/index.js
> +export const fetchTopReviews = async (count = 5) => {
We can make this 10 to match the number of restaurants retrieved by Google in the restaurants page. Also, could pull out this number into a constant to make it easier to manage in the future

2024-12-06 04:06 UTC, Justdoit2 commented on src/containers/RecentReviews/index.js
> +const GOOGLE_API_PATH = "https://places.googleapis.com/v1/";
added the export const to the saga files

2024-12-10 05:57 UTC, NickPriv approved these changes

2024-12-10 05:57 UTC, oxyflush approved these changes

2024-12-10 05:58 UTC, merged